package com.skillos.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import com.fasterxml.jackson.annotation.JsonIgnore;

import java.time.LocalDateTime;

/**
 * Represents a single flashcard used in the Study Mode.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "flashcards")
public class Flashcard {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The user who owns this flashcard
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    @JsonIgnore
    private User user;

    // The roadmap this flashcard was automatically mapped to (can be null if manually created without a link)
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "roadmap_id")
    @JsonIgnore
    private Roadmap roadmap;

    // The specific skill this flashcard is associated with (e.g., "Python")
    @Column(name = "skill_name")
    private String skillName;

    // The front side of the flashcard
    @Column(nullable = false, columnDefinition = "TEXT")
    private String question;

    // The back side of the flashcard
    @Column(nullable = false, columnDefinition = "TEXT")
    private String answer;

    // Current difficulty level; null until the user reviews it for the first time
    @Column(columnDefinition = "enum('easy','medium','hard','forgot')")
    private String difficulty;

    // Mastery percentage (0 to 100), increases as the user studies it successfully
    @Column(nullable = false)
    private Integer mastery = 0;

    // Tracks if this was generated by Gemini API or manually typed by the user
    @Column(nullable = false, columnDefinition = "enum('auto_generated','manual') DEFAULT 'manual'")
    private String source = "manual";

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}
