spring.application.name=SkillOS Backend
server.port=8080
server.address=0.0.0.0

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/skillos_v1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
#Shows SQL queries
spring.jpa.show-sql=true
#My Sql dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#Formats SQL queries
spring.jpa.properties.hibernate.format_sql=true

# JWT Settings
application.security.jwt.secret-key=SkillOS2026SecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLong!!
application.security.jwt.expiration=86400000

# Swagger OpenAPI settings
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Gemini AI API
application.gemini.api-key=
application.gemini.model=gemini-3.6-flash
